#配置数据源的属性
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/erp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: 897910256
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true
   #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow: #IP白名单
        deny:  #IP黑名单
        url-pattern: /druid/*
#      web-stat-filter: 
#        enabled: true
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  thymeleaf:
    cache: false
    #以下都是默认的配置可以不用配置
    #prefix: classpath:/templates/
    #suffix: .html
    #encoding: UTF-8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss #前端传递日期字符串到后台转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #后端传递日期到前端展示 
    time-zone:  GMT+8
  #文件上传相关配置
  servlet:
    multipart:
      enabled: true
      #location: D:/upload/
      max-file-size: 100MB #只能大写
      max-request-size: 100MB

#Mybatis的配置文件
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
  - classpath:mybatis/mapper/*Mapper.xml
  
#shiro配置
shiro:
  hash-algorithm: MD5
  hash-iterations: 2
  anons-urls:
   - /index.html*
   - /System/toLogin*
   - /Login/login
   - /resource/**
  login-url: /index.html
# logout-url: /Login/logout*
  authc-urls:
  - /**
  
  
 #redis配置

 